apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_PASSWORD: YmlsYWwxMjM0Cg==
  MYSQL_DATABASE: cGhvbmVib29rCg==
  MYSQL_USER: bmloYXQK
  MYSQL_ROOT_PASSWORD: bmloYXQxMjM0NTYK
